kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: sand-cluster
  version: "1.23"
  region: us-east-1
availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      wellKnownPolicies:
        autoScaler: true
      roleName: sand-autoscaler-role
    - metadata:
        name: aws-load-balancer-controller
        namespace: aws-system
      wellKnownPolicies:
        awsLoadBalancerController: true
      roleName: sand-lb-controller-role
    - metadata:
        name: aws-cloudwatch-agent
        namespace: aws-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      roleName: sand-cloudwatch-metrics
    - metadata:
        name: aws-fluent-bit
        namespace: aws-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      roleName: sand-fluent-bit
addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
gitops:
  flux:
    gitProvider: github
    flags:
      owner: demians12
      repository: kubernetes-flux
      branch: demo
      path: ./clusters/sand-cluster/
      namespace: flux-system
managedNodeGroups:
  - name: ng-workers
    labels: {role: workers}
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    volumeSize: 80
    privateNetworking: true

